source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
# ↓ edited ↓
# gem "jekyll", "~> 4.2.0"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
# gem "minima", "~> 2.5"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# ↓ edited ↓
# gem "github-pages", group: :jekyll_plugins
gem "github-pages", "~> 215", group: :jekyll_plugins

# —————————————————————
#
# Jekyll theme
#
# just-the-docs · ↓ using pmarsceill · https://github.com/pmarsceill/just-the-docs · gem
# gem "just-the-docs"
#
# just-the-docs · ↓ Using Yummly Forked version
gem 'just-the-docs', '0.3.3', git: 'https://github.com/yummly/just-the-docs/'
#
# —————————————————————

# ↓ other requirement (it seems webrick was not installed by default anymore)
gem "webrick", "~> 1.7"
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
